**Data QA pipelines:  Extraction and cleaning of data of pollution of us from year 2000 to 2016**

In this notebook, I extract data from a csv file and apply quality assurance rules in cleaning and preparing the dataset for analysis.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
sn.set()

In [ ]:
df=pd.read_csv('/pollution_us_2000_2016.csv')
df.head()

,Unnamed: 0,State Code,County Code,Site Num,Address,State,County,City,Date Local,NO2 Units,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
0,0,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,01-01-2000,Parts per billion,...,Parts per billion,3.000000,9.0,21,13.0,Parts per million,1.145833,4.2,21,NaN
1,1,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,01-01-2000,Parts per billion,...,Parts per billion,3.000000,9.0,21,13.0,Parts per million,0.878947,2.2,23,25.0
2,2,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,01-01-2000,Parts per billion,...,Parts per billion,2.975000,6.6,23,NaN,Parts per million,1.145833,4.2,21,NaN
3,3,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,01-01-2000,Parts per billion,...,Parts per billion,2.975000,6.6,23,NaN,Parts per million,0.878947,2.2,23,25.0
4,4,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,02-01-2000,Parts per billion,...,Parts per billion,1.958333,3.0,22,4.0,Parts per million,0.850000,1.6,23,NaN

In [ ]:
del df['Unnamed: 0']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.info()
df.isnull().sum()
df.duplicated().sum()
df.describe(include='all')
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 29 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Unnamed: 0         1048575 non-null  int64
 1   State Code         1048575 non-null  int64
 2   County Code        1048575 non-null  int64
 3   Site Num           1048575 non-null  int64
 4   Address            1048575 non-null  object
 5   State              1048575 non-null  object
 6   County             1048575 non-null  object
 7   City               1048575 non-null  object
 8   Date Local         1048575 non-null  object
 9   NO2 Units          1048575 non-null  object
 10  NO2 Mean           1048575 non-null  float64
 11  NO2 1st Max Value  1048575 non-null  float64
 12  NO2 1st Max Hour   1048575 non-null  int64
 13  NO2 AQI            1048575 non-null  int64
 14  O3 Units           1048575 non-null  object
 15  O3 Mean            1048575 non-null  float64
 16  O3 1st Max Value   1048575 non-null  float64
 17  O3 1st Max Hour    1048575 non-null  int64
 18  O3 AQI             1048575 non-null  int64
 19  SO2 Units          1048575 non-null  object
 20  SO2 Mean           1048575 non-null  float64
 21  SO2 1st Max Value  1048575 non-null  float64
 22  SO2 1st Max Hour   1048575 non-null  int64
 23  SO2 AQI            524489 non-null   float64
 24  CO Units           1048575 non-null  object
 25  CO Mean            1048575 non-null  float64
 26  CO 1st Max Value   1048575 non-null  float64
 27  CO 1st Max Hour    1048575 non-null  int64
 28  CO AQI             524352 non-null   float64
dtypes: float64(10), int64(10), object(9)
memory usage: 232.0+ MB
Unnamed: 0: 119549 unique values
State Code: 37 unique values
County Code: 60 unique values
Site Num: 93 unique values
Address: 159 unique values
State: 37 unique values
County: 105 unique values
City: 120 unique values
Date Local: 4018 unique values
NO2 Units: 1 unique values
NO2 Mean: 14001 unique values
NO2 1st Max Value: 846 unique values
NO2 1st Max Hour: 24 unique values
NO2 AQI: 129 unique values
O3 Units: 1 unique values
O3 Mean: 6965 unique values
O3 1st Max Value: 134 unique values
O3 1st Max Hour: 24 unique values
O3 AQI: 116 unique values
SO2 Units: 1 unique values
SO2 Mean: 9308 unique values
SO2 1st Max Value: 791 unique values
SO2 1st Max Hour: 24 unique values
SO2 AQI: 140 unique values
CO Units: 1 unique values
CO Mean: 12559 unique values
CO 1st Max Value: 1480 unique values
CO 1st Max Hour: 24 unique values
CO AQI: 107 unique values

In [ ]:
df1=df.dropna()
df1.isnull().sum()
df1.describe(include='all')

,Unnamed: 0,State Code,County Code,Site Num,Address,State,County,City,Date Local,NO2 Units,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
count,262273.000000,262273.000000,262273.000000,262273.000000,262273,262273,262273,262273,262273,262273,...,262273,262273.000000,262273.000000,262273.000000,262273.000000,262273,262273.000000,262273.000000,262273.00000,262273.000000
unique,NaN,NaN,NaN,NaN,159,37,105,120,4018,1,...,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,1130 EASTWAY DRIVE,California,Los Angeles,Not in a city,10-06-2002,Parts per billion,...,Parts per billion,NaN,NaN,NaN,NaN,Parts per million,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,5020,99440,16403,16358,160,262273,...,262273,NaN,NaN,NaN,NaN,262273,NaN,NaN,NaN,NaN
mean,48487.368223,21.297164,69.787054,1249.338251,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.500730,6.959576,8.456940,9.675735,NaN,0.423953,0.617218,6.76306,7.026652
std,28987.703239,17.101597,69.897562,2103.296921,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.223487,10.456134,6.768454,13.753711,NaN,0.362818,0.588941,7.98954,6.724625
min,1.000000,4.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.454545,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.00000,0.000000
25%,23824.000000,6.000000,19.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.476190,1.000000,2.000000,1.000000,NaN,0.200000,0.300000,0.00000,3.000000
50%,47661.000000,17.000000,67.000000,80.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.434783,3.500000,8.000000,4.000000,NaN,0.341667,0.500000,4.00000,6.000000
75%,71493.000000,38.000000,95.000000,2002.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.291667,8.000000,13.000000,11.000000,NaN,0.545833,0.800000,10.00000,9.000000
max,119547.000000,80.000000,510.000000,9997.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,321.625000,351.000000,23.000000,200.000000,NaN,7.508333,15.500000,23.00000,201.000000

In [ ]:
def cleaning_outlier(df,columns,factor=1.5):
    df2=df1.copy()
    for x in columns:
            Q1=df2[x].quantile(0.25)
            Q3=df2[x].quantile(0.75)
            IQR=Q3-Q1
            LOWER_BOUND=Q1-1.5*IQR
            UPPER_BOUND=Q3+1.5*IQR
            df2=df2[(df2[x]>=LOWER_BOUND)&(df2[x]<=UPPER_BOUND)]
    return df2
df3=cleaning_outlier(df,columns=['NO2 Mean', 'NO2 1st Max Value', 'NO2 1st Max Hour', 'NO2 AQI', 'O3 Mean', 'O3 1st Max Value', 'O3 1st Max Hour', 'O3 AQI', 'SO2 Mean', 'SO2 1st Max Value', 'SO2 1st Max Hour', 'SO2 AQI', 'CO Mean', 'CO 1st Max Value', 'CO 1st Max Hour', 'CO AQI'])
df3.describe()

,Unnamed: 0,State Code,County Code,Site Num,NO2 Mean,NO2 1st Max Value,NO2 1st Max Hour,NO2 AQI,O3 Mean,O3 1st Max Value,O3 1st Max Hour,O3 AQI,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
count,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000
mean,46408.160134,19.654854,69.176715,1316.736288,11.601319,23.968436,11.970368,22.604964,0.026358,0.039400,9.933242,33.613547,1.360739,3.262901,7.819750,4.508704,0.324130,0.452496,6.451078,5.144441
std,29483.070273,16.932397,64.152136,2096.890045,7.516033,13.634523,8.040273,12.898334,0.009808,0.012019,1.393154,10.680789,1.359821,2.851636,6.788143,4.172833,0.201544,0.283830,7.964087,3.326054
min,5.000000,4.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000417,0.002000,6.000000,2.000000,-0.454545,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21930.500000,6.000000,19.000000,9.000000,5.869565,13.000000,5.000000,12.000000,0.019333,0.031000,9.000000,26.000000,0.260870,1.000000,1.000000,1.000000,0.187500,0.200000,0.000000,2.000000
50%,42967.000000,8.000000,67.000000,133.000000,10.291667,23.000000,10.000000,22.000000,0.026333,0.039000,10.000000,33.000000,1.000000,2.000000,7.000000,3.000000,0.300000,0.400000,2.000000,5.000000
75%,69717.000000,37.000000,95.000000,2002.000000,16.130435,34.000000,20.000000,32.000000,0.033250,0.048000,11.000000,41.000000,2.012500,5.000000,12.000000,7.000000,0.445833,0.600000,10.000000,7.000000
max,119432.000000,80.000000,510.000000,9997.000000,38.739130,68.600000,23.000000,66.000000,0.057958,0.064000,14.000000,64.000000,6.979167,11.900000,23.000000,16.000000,0.970588,1.200000,23.000000,14.000000

In [ ]:
df3.isnull().sum()
df3.describe()

,Unnamed: 0,State Code,County Code,Site Num,NO2 Mean,NO2 1st Max Value,NO2 1st Max Hour,NO2 AQI,O3 Mean,O3 1st Max Value,O3 1st Max Hour,O3 AQI,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
count,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000,153315.000000
mean,46408.160134,19.654854,69.176715,1316.736288,11.601319,23.968436,11.970368,22.604964,0.026358,0.039400,9.933242,33.613547,1.360739,3.262901,7.819750,4.508704,0.324130,0.452496,6.451078,5.144441
std,29483.070273,16.932397,64.152136,2096.890045,7.516033,13.634523,8.040273,12.898334,0.009808,0.012019,1.393154,10.680789,1.359821,2.851636,6.788143,4.172833,0.201544,0.283830,7.964087,3.326054
min,5.000000,4.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000417,0.002000,6.000000,2.000000,-0.454545,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21930.500000,6.000000,19.000000,9.000000,5.869565,13.000000,5.000000,12.000000,0.019333,0.031000,9.000000,26.000000,0.260870,1.000000,1.000000,1.000000,0.187500,0.200000,0.000000,2.000000
50%,42967.000000,8.000000,67.000000,133.000000,10.291667,23.000000,10.000000,22.000000,0.026333,0.039000,10.000000,33.000000,1.000000,2.000000,7.000000,3.000000,0.300000,0.400000,2.000000,5.000000
75%,69717.000000,37.000000,95.000000,2002.000000,16.130435,34.000000,20.000000,32.000000,0.033250,0.048000,11.000000,41.000000,2.012500,5.000000,12.000000,7.000000,0.445833,0.600000,10.000000,7.000000
max,119432.000000,80.000000,510.000000,9997.000000,38.739130,68.600000,23.000000,66.000000,0.057958,0.064000,14.000000,64.000000,6.979167,11.900000,23.000000,16.000000,0.970588,1.200000,23.000000,14.000000

In [ ]:
df3.duplicated().sum()
df3=df3.drop_duplicates()
df3.duplicated().sum()
df3['Date Local']=pd.to_datetime(df3['Date Local'],format='%d-%m-%Y')
df3.to_csv(r'Cleaned_pollution_data.csv', index=False)